small small widget changes
CDCgov/cfa-ngm-widget pull request #60
Opened 2024-12-18 22:58 UTC by paigemiller

addressing https://github.com/CDCgov/cfa-ngm-widget/issues/57

2024-12-20 20:10 UTC, afmagee42 requested changes
I like the changes but we need to align text and computation re: % vaccinated

2024-12-20 20:10 UTC, afmagee42 commented on scripts/widget.py
> +    prop_vax_help = f"Based on allocated doses, what percent of each group is successfully immune? In the counter factual scenario, we assume no vaccines are administered. Vaccination of 100% does no
I'm happy for us to report successful vaccinations but that is not what is currently being computed.

E.g. with default of 500k core getting 250k vaccines at VE 0.74, this reports 50% vaccination.

2024-12-20 20:10 UTC, afmagee42 commented on scripts/widget.py
> +    summary_help = (
I like moving this out and only printing it once. Reduces bloat.

2024-12-23 16:14 UTC, swo approved these changes
LGTM, but I defer to @paigemiller and @afmagee42

2024-12-23 17:17 UTC, swo commented
@afmagee42 I'm merging on @paigemiller 's request; if you have further edits, we can do them in a future PR

2024-12-23 17:17 UTC, merged